### PR TITLE
fix: Bring back app drawer multiple lines logic

### LINKED ISSUE #6310: [BUG] Lawnchair v16 - App Drawer - Using multiple lines does not work
### Describe the bug

I have enabled the “Use multiple lines” feature, but the app names are still displayed on a single line.

### Steps to reproduce

1. Go to Settings -> App Drawer and enable "using mutiple lines"
2. Open App Drawer and check the app names

### Expected behavior

When the function is activated, the app names should also be displayed on multiple lines.

### Screenshots

Image

### Device information

- Device: Google Pixel 8
- OS: Android 16
- Build: BP4A.260105.004.E1

### App version

16.0.0-20260124 from Goooler

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by VBansal99**
### Description
This PR fixes the issue #6310 where enabling "Use multiple lines" in the App Drawer did not display app names on multiple lines.  

Fixes #6310
### Testing
1. Go to Settings → App Drawer.
2. Enable the "Use multiple lines" toggle.
3. Open the App Drawer and verify that app names are now displayed on two lines.
4. Disable the toggle App Drawer switches back to single-line app names.

### CODE REVIEW

**Comment by VBansal99** [comment]
@MrSluffy please review this

**Comment by VBansal99** [comment]
@SuperDragonXD please review this

**Comment by SuperDragonXD** [comment]
Actually, the build error seens like it's a caching issue. Will check in a bit.

File: lawnchair/src/app/lawnchair/preferences2/PreferenceManager2.kt [hunk 1]
```diff
@@ -595,7 +597,10 @@ class PreferenceManager2 @Inject constructor(
     val twoLineAllApps = preference(
         key = booleanPreferencesKey(name = "two_line_all_apps"),
         defaultValue = context.resources.getBoolean(R.bool.config_default_enable_two_line_allapps),
-        onSet = { reloadHelper.recreate() },
+        onSet = { value ->
+            LauncherPrefs.get(context).put(ENABLE_TWOLINE_ALLAPPS_TOGGLE, value)
+            reloadHelper.recreate()
```
Comment (validcube) [inline lawnchair/src/app/lawnchair/preferences2/PreferenceManager2.kt]:
```suggestion
```

Launcher3 already listen to this prefs so recreate isn't needed anymore.

**Review by validcube — APPROVED** [review]
💫🧑‍💻 LGTM with minor adjustment.

**Comment by Goooler** [comment]
Next time, mark `Fixes #6310` instead of `Fixes (#6310)`.
