### PR TITLE
Fix alignment of app drawer folders when multiline app names enabled

### LINKED ISSUE #1832: App drawer folder icons misaligned when multiline app names enabled
## Description

When multiline app names are enabled for the app drawer, folders are placed slightly higher than other app icons.

## Expected Behavior

All icons in the app drawer are aligned.

## Actual Behavior

Folders are not aligned with other app icons.

nofolder-single | nofolder-multi
:-------------------------:|:-------------------------:
folder-single | folder-multi

## Steps to Reproduce

1. Turn on Multiline app names in the App drawer
2. Turn on Folders Categorisation in the App drawer
3. Make a folder with some apps inside

## Environment

* Device: Samsung Galaxy S10 + Pixel 2 Emulator
* Android version: Android 9
* Launcher version: Launcher version 2.0-2551, and Launcher revision 3b2417339
* Rom: OneUI 1.1 + Stock Pixel 2 Emulator

### PR DESCRIPTION
**Pull request by Shingyx**
The FolderIcon container's height is already set to allAppsCellHeightPx in AllAppsGridAdapter, so use match_parent to set the correct height on the FolderIcon. Then vertically align by matching BubbleTextView's onMeasure implementation.

BubbleTextView's onMeasure implementation looks like this:
https://github.com/LawnchairLauncher/Lawnchair/blob/3b24173397f6d77a5bdd9ef2e40cf8ff7c67efc9/src/com/android/launcher3/BubbleTextView.java#L526-L537

Resolves https://github.com/LawnchairLauncher/Lawnchair/issues/1832.

Before | After
|-|-|
before-multi | after

Inspector Before | Inspector After
|-|-|
inspector-before | inspector-after

### CODE REVIEW

File: src/com/android/launcher3/folder/FolderIcon.java [hunk 1]
```diff
@@ -657,6 +653,24 @@ protected boolean verifyDrawable(@NonNull Drawable who) {
         return mPreviewItemManager.verifyDrawable(who) || super.verifyDrawable(who);
     }
 
+    @Override
+    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
+        if (!mInfo.useIconMode(mLauncher)) {
```
Comment (suphon-t) [inline src/com/android/launcher3/folder/FolderIcon.java]: Can you add a check to make this only run for folders in the app drawer?

**Review by suphon-t — CHANGES_REQUESTED** [review]

**Review by suphon-t — APPROVED** [review]
