### PR TITLE
fix(allapps): Hide app drawer folders in work/private profiles

### LINKED ISSUE #5234: [BUG] App Drawer Folders Showing in Both Default and Work Profile
### Describe the bug

App drawer folders are visible in both the default and work profiles. However, the folders contain only apps from the default profile. Folders should only be displayed in the default profile if they do not contain work profile apps.

### Steps to reproduce

1. Create an app drawer folder and add some apps from the default profile.
2. The folder appears in both the default and work profiles.

### Expected behavior

App folders should only appear in the profile where they contain relevant apps.
If a folder contains only default profile apps, it should not be visible in the work profile.

### Screenshots

_No response_

### Device information

- App version: 15

### Additional context

_No response_

### LINKED ISSUE #5425: [BUG] App drawer folders replicating in private space
### Describe the bug

Hello,
I'm using Lawnchair 15 nightly on GrapheneOS and get a strange behaviour.
If i create folders on app drawer (main profile) the folder and the apps inside are replicated two times in private space, once with third party installed apps, and once in a subcategory with graphene system apps, though they are not even installed in private space..
And since i have a folder with GrapheneOS apps i have then three times these apps in private space (without name difference).

Also it's complicated when selecting apps for a folder with the ones that are installed in both public and private spaces because they all appear in same list without differentiation in names.

Would be great to have a seperate folder management for public and private space!

### Steps to reproduce

1. Create folders on app drawer
2. Open private space
3. See replicated folders and apps

### Expected behavior

The folders created with public apps should not be replicated on private space.

### Screenshots

Image
Image

### Device information

- Device: Google Pixel 9 Pro
- OS: Graphene OS 15
- App version: Lawnchair 15.dev nightly build 2176

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SuperDragonXD**
### Description

Prevents app drawer folders from being displayed within the work or private space profiles to avoid state complexity.

- Fixes #5425
- Fixes #5234

### Testing

1. Enable both work profile and private space.
2. Create an app drawer folder with any items.
3. Check app drawer work profile and private space - notice that it only shows up on the Personal (default) profile.

### Type of change

:white_check_mark: **Bug fix** (A non-breaking change that fixes an issue)
:x: **New feature** (A non-breaking change that adds functionality)
:x: **Breaking change** (A fix or feature that would cause existing functionality to not work as expected)
:x: **Refactor** (A code change that neither fixes a bug nor adds a feature)
:x: **Performance** (A code change that improves performance)
:x: **Style** (Code style changes)
:x: **Docs** (Changes to documentation)
:x: **Chore** (Changes to the build process or other tooling)

### CODE REVIEW

File: src/com/android/launcher3/allapps/AlphabeticalAppsList.java [hunk 1]
```diff
@@ -431,6 +431,21 @@ protected int addAppsWithSections(List<AppInfo> appList, int startPosition) {
...
+     */
+    protected boolean isWorkOrPrivateSpace(List<AppInfo> appList) {
+        PrivateProfileManager mPrivateProfileManager = getPrivateProfileManager();
+        if (appList.isEmpty()) {
+            return false;
+        }
+        return appList.stream().anyMatch(info ->
+                (mWorkProviderManager != null && mWorkProviderManager.getItemInfoMatcher().test(info))
+                        || (mPrivateProfileManager != null
+                        && mPrivateProfileManager.getItemInfoMatcher().test(info)));
```
Comment (Goooler) [inline src/com/android/launcher3/allapps/AlphabeticalAppsList.java]:
```suggestion
        var ppm = getPrivateProfileManager();
        if (appList.isEmpty()) {
            return false;
        }
        return appList.stream().anyMatch(info ->
                (ppm != null && ppm.getItemInfoMatcher().test(info))
                        || (ppm != null
                        && ppm.getItemInfoMatcher().test(info)));
```

**Review by Goooler — APPROVED** [review]

File: src/com/android/launcher3/allapps/AlphabeticalAppsList.java (hunk 1 above)
Comment (SuperDragonXD) [reply src/com/android/launcher3/allapps/AlphabeticalAppsList.java]: Could you clarify why you simplified this? We also need to check if the app also belongs to the Work profile, as checking only Private Space is not enough for this behavior.

Comment (Goooler) [reply src/com/android/launcher3/allapps/AlphabeticalAppsList.java]: Just for renaming.

Comment (SuperDragonXD) [reply src/com/android/launcher3/allapps/AlphabeticalAppsList.java]: I see. Also just realized that I can simplify this further:

```java
    protected boolean isWorkOrPrivateSpace(List<AppInfo> appList) {
        if (appList.isEmpty()) {
            return false;
        }
        return appList.stream().anyMatch(info ->
                (mWorkProviderManager != null && mWorkProviderManager.getItemInfoMatcher().test(info))
                        || (mPrivateProviderManager != null
                        && mPrivateProviderManager.getItemInfoMatcher().test(info)));
    }
```

Would this be fine instead, or do you want me to put the maangers into variables?

Comment (Goooler) [reply src/com/android/launcher3/allapps/AlphabeticalAppsList.java]: `mWorkProviderManager` should not start with `m`.

Comment (SuperDragonXD) [reply src/com/android/launcher3/allapps/AlphabeticalAppsList.java]: Unfortunately, that seems to be the naming near the start of the class: 

```java
public class AlphabeticalAppsList<T extends Context & ActivityContext> implements
        AllAppsStore.OnUpdateListener {

    public static final String TAG = "AlphabeticalAppsList";

    private final WorkProfileManager mWorkProviderManager;

    private final PrivateProfileManager mPrivateProviderManager;
    
    ...
```

So should I just keep it as is or do something else?

Comment (Goooler) [reply src/com/android/launcher3/allapps/AlphabeticalAppsList.java]: I meant that at least the local variable should not be named start with `m`.

Comment (SuperDragonXD) [reply src/com/android/launcher3/allapps/AlphabeticalAppsList.java]: Okay. I guess I can just simplify this (as seen above), then merge. Thanks.

**Comment by ghost** [comment]
i tried that commit with Lawnchair.Debug.15-dev.Nightly-CI_2832-dd786af.apk and it is totally bugged, now folders don't work in main and still show in work and private, tried to reset folders but it dont help., pixel android 16

**Comment by iArisu** [comment]
Can confirm, Samsung Android 12 OneUI 4
