### PR TITLE
Always enable `GoogleQsbContainerView` if it is the current search widget

### LINKED ISSUE #3210: [BUG] Google Search Widget disappears if "At a Glance" is turned off
### Describe the bug

Describe the bug
Google search dock widget is blank if At a Glance is disabled in Lawnchair settings.

### Steps to reproduce

1.Go to Dock settings, select Google Search Bar as Search Bar Widget
2.Search Bar changes successfully
3.Go to At a Glance Settings, turn off Show on Home Screen
4.Dock now has blank space where the Search Bar Widget was.

### Expected behavior

Search Bar Widget should still be showing up regardless of what At a Glance settings are.

### Screenshots

_No response_

### Device information

- Device: OnePlus 8
- OS: CrDroid 8.5 (Android 12)
- App version:  12.1.0 Dev

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Goooler**
## Description

Follow up #3108, closes #3210.

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: lawnchair/src/app/lawnchair/qsb/GoogleQsbContainerView.kt [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+import android.util.AttributeSet
+import com.android.launcher3.qsb.QsbContainerView
+
+class GoogleQsbContainerView @JvmOverloads constructor(
+    context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
+) : QsbContainerView(context, attrs, defStyleAttr) {
+
+    class SmartSpaceFragment : QsbFragment() {
+        override fun isQsbEnabled(): Boolean = true
+    }
```
Comment (Goooler) [inline lawnchair/src/app/lawnchair/qsb/GoogleQsbContainerView.kt:13]: Default value before:

https://github.com/LawnchairLauncher/lawnchair/blob/d52c5744272941033a5cda18dfd0e9817e0e5a07/src/com/android/launcher3/qsb/QsbContainerView.java#L298-L300

File: lawnchair/src/app/lawnchair/qsb/GoogleQsbContainerView.kt [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+import android.content.Context
+import android.util.AttributeSet
+import com.android.launcher3.qsb.QsbContainerView
+
+class GoogleQsbContainerView @JvmOverloads constructor(
+    context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
+) : QsbContainerView(context, attrs, defStyleAttr) {
+
+    class QsbFragment : QsbContainerView.QsbFragment() {
+        override fun isQsbEnabled(): Boolean = true
```
Comment (Goooler) [inline lawnchair/src/app/lawnchair/qsb/GoogleQsbContainerView.kt:12]: Default value before:

https://github.com/LawnchairLauncher/lawnchair/blob/d52c5744272941033a5cda18dfd0e9817e0e5a07/src/com/android/launcher3/qsb/QsbContainerView.java#L298-L300

https://github.com/LawnchairLauncher/lawnchair/blob/1f5597a908f0ecc8dcebbe0253d7114b69a9ab45/src/com/android/launcher3/config/FeatureFlags.java#L61-L64

**Review by SuperDragonXD — APPROVED** [review]

**Review by yasanglass — APPROVED** [review]
