### PR TITLE
Fix NPE in DepthController

### LINKED ISSUE #3111: [BUG] NPE in PrefenceMananger2$Companion.getInstance
### Describe the bug

Always return null pointer exception from getInstance

### Expected behavior

Should no have crash in getInstance

### Screenshots

_No response_

### Device information

- Device: Motoral Kiev, Samsung A03su, Samsung A12s, Samsung A12u, Samsung A13x, Samsung A21s, , Samsung b0q, Samsung d2s, Samsung r9q
- OS: Android version 11,12,13
- App version: 12.1

### Additional context

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3914)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4201)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2438)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8669)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
  at android.content.ContextWrapper.getApplicationContext (ContextWrapper.java:129)
  at com.android.launcher3.util.MainThreadInitializedObject.get (MainThreadInitializedObject.java:57)
  at app.lawnchair.preferences2.PreferenceManager2$Companion.getInstance (PreferenceManager2.kt:408)
  at app.lawnchair.preferences2.PreferenceManager2.getInstance (PreferenceManager2.kt)
  at com.android.launcher3.statehandlers.DepthController.<init> (DepthController.java:177)
  at com.android.launcher3.BaseQuickstepLauncher.<init> (BaseQuickstepLauncher.java:103)
  at com.android.launcher3.uioverrides.QuickstepLauncher.<init> (QuickstepLauncher.java:94)
  at app.lawnchair.LawnchairLauncher.<init> (LawnchairLauncher.kt:142)
  at java.lang.Class.newInstance (Class.java)
  at android.app.AppComponentFactory.instantiateActivity (AppComponentFactory.java:95)
  at androidx.core.app.CoreComponentFactory.instantiateActivity (CoreComponentFactory.java:45)
  at android.app.Instrumentation.newActivity (Instrumentation.java:1273)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3901)
```

### PR DESCRIPTION
**Pull request by Goooler**
## Description

Fixes #3111

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: src/com/android/launcher3/util/MainThreadInitializedObject.java [hunk 1]
```diff
@@ -56,8 +58,17 @@ public T get(Context context) {
 
         if (mValue == null) {
             if (Looper.myLooper() == Looper.getMainLooper()) {
+                Context app;
+                try {
+                    app = context.getApplicationContext();
+                } catch (Exception ignored) {
+                    // https://github.com/LawnchairLauncher/lawnchair/issues/3111
+                    app = LawnchairApp.getInstance();
+                }
```
Comment (Goooler) [inline src/com/android/launcher3/util/MainThreadInitializedObject.java]: This NPE may occur when `LawnchairLauncher` is restarting.

The other workaround is run `MAIN_EXECUTOR.submit(() -> get(context)).get()` again, WDYT?

**Comment by Goooler** [comment]
CC @liu-wanshun

File: quickstep/src/com/android/launcher3/statehandlers/DepthController.java [hunk 2]
```diff
@@ -174,7 +175,9 @@ public void run() {
 
     public DepthController(Launcher l) {
         mLauncher = l;
-        Preference<Boolean, Boolean, ?> depthPref = PreferenceManager2.getInstance(l).getWallpaperDepthEffect();
+        // TODO: No need to use app context here after merging Android 13 branch.
+        // https://cs.android.com/android/platform/superproject/+/master:packages/apps/Launcher3/quickstep/src/com/android/launcher3/uioverrides/QuickstepLauncher.java;drc=eef0b1640bbc8c26c824836271a71b929726e895;l=175
+        Preference<Boolean, Boolean, ?> depthPref = PreferenceManager2.getInstance(LawnchairApp.getInstance()).getWallpaperDepthEffect();
```
Comment (Goooler) [inline quickstep/src/com/android/launcher3/statehandlers/DepthController.java:180]: Android 12.1: https://github.com/LawnchairLauncher/lawnchair/blob/4a3ce2b120be095679795c821790624d1d5532a5/quickstep/src/com/android/launcher3/BaseQuickstepLauncher.java#L103

Android 13: https://cs.android.com/android/platform/superproject/+/master:packages/apps/Launcher3/quickstep/src/com/android/launcher3/uioverrides/QuickstepLauncher.java;drc=eef0b1640bbc8c26c824836271a71b929726e895;l=175

**Review by liu-wanshun — APPROVED** [review]
