### PR TITLE
fix: Window Insets crashes on less than Android 11

### LINKED ISSUE #6047: [BUG] Lawnchair 15 Nightly crashed during window refresh Android 9
### Describe the bug

Lawnchair 15 Nightly crashed while I'm using some apps that likely triggers window refresh, for example Oppo Phone Manager app on my Oppo A1k with ColorOS 6.0.1.

### Steps to reproduce

1. Open the security app that likely triggers screen redraw or window refresh (e.g. Phone Manager on Oppo devices)
2. Go to System Boost or any features in the app
3. Wait until window refreshing on background or Lawnchair crashed on background 

### Expected behavior

It should keep Lawnchair running properly during that window refresh or screen redraw, while using those security or phone manager apps that preloaded on some device manufacturers running on Android Pie and below during storage clean-up or anything else on there. 

### Screenshots

_No response_

### Device information

Oppo A1k; running Android 9 with ColorOS 6.0.1

### App version

15 Dev #2909

### Additional context

Here's the crash log of this crash. I'll attach the file below. 

[Lawnchair bug report 3 Nov 2025 21:37:58.txt](https://github.com/user-attachments/files/23305132/Lawnchair.bug.report.3.Nov.2025.21.37.58.txt)

### PR DESCRIPTION
**Pull request by validcube**
### Description

Fixes #6047

### Reasoning

At some time ago, AOSP removes compatibility code for device older than Android 11

This restores that change.

~~Unlike the changes in 16-dev, this time I remember to import the dependencies~~

### Type of change

:white_check_mark: **Bug fix** (A non-breaking change that fixes an issue)

### CODE REVIEW

File: src/com/android/launcher3/widget/AddItemWidgetsBottomSheet.java [hunk 1]
```diff
@@ -153,13 +155,20 @@ protected int getScrimColor(Context context) {
...
+                    mContent.getPaddingEnd(), mInsets.bottom);
+        } else {
+            mInsets.set(windowInsets.getSystemWindowInsetLeft(),
+                windowInsets.getSystemWindowInsetTop(),
+                windowInsets.getSystemWindowInsetRight(),
+                windowInsets.getSystemWindowInsetBottom());
+        }
         int contentHorizontalMarginInPx = getResources().getDimensionPixelSize(
-                R.dimen.widget_list_horizontal_margin);
+            R.dimen.widget_list_horizontal_margin);
```
Comment (validcube) [inline src/com/android/launcher3/widget/AddItemWidgetsBottomSheet.java]:
```suggestion
                R.dimen.widget_list_horizontal_margin);
```

**Review by Goooler — APPROVED** [review]
