### PR TITLE
Patches for crashes in Android Q, R and S

### LINKED ISSUE #2820: [BUG] [META] Adding widgets causes Lawnchair to crash
### Describe the bug

This is a meta issue for all the widget crashing issues *relating to this crash message*: `java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference`. All issues relating to this will be closed and will be linked to this meta issue.

### Steps to reproduce

1. Go to the widgets menu
2. Find a widget, and add it to the home screen
3. See error

### Expected behavior

Lawnchair should not crash, or if there's an internal error, simply discard the attempt to add the widget.

### Screenshots

Note: Crash notification didn't appear since I muted notifications

https://user-images.githubusercontent.com/70206496/183589954-cffc0191-a399-4a83-9e48-0e804e497c9f.mp4

### Device information

- Device: Multiple Devices
- OS: Any OS that supports widgets and Lawnchair
- App version 11+

### Additional context

Here are the things that increases the chance Lawnchair will crash and show this specific error:

* Lawnchair is set as the default launcher
* The widget has a setup screen

### LINKED ISSUE #3744: [BUG] Lawnchair 13 debug crashing when opening
### Describe the bug

My tablet running android 12 immediately crash the newest debug version. I tried other versions but they keep crashing in the last one (12.1) 

### Steps to reproduce

1. Go to 'Lawnchiar.'
2. See error

### Expected behavior

Supposed to open the launcher without any problems

### Screenshots

_No response_

### Device information

- Device: [Teclast t40 pro]
- OS: [Android version 12.0]
- App version: [Lawnchair 13 debug]

### Additional context

Lawnchair (Debug) bug report 18 Nov 2023 10:37:21 pm
version: 13 Dev (#2325) (13)
commit: bd0da95
build.brand: Teclast
build.device: T40Pro_2022_EEA
build.display: V1.02_20230826
build.fingerprint: Teclast/T40Pro_2022_EEA/T40Pro_2022_EEA:12/SP1A.210812.016/221010:user/release-keys
build.hardware: ums9230_1h10
build.id: SP1A.210812.016
build.manufacturer: Teclast
build.model: T40 Pro_EEA
build.product: T40Pro_2022_EEA
build.type: user
version.codename: REL
version.incremental: 221010
version.release: 12
version.sdk_int: 31
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.NoSuchMethodError: No virtual method getOnBackInvokedDispatcher()Landroid/window/OnBackInvokedDispatcher; in class Lcom/android/launcher3/uioverrides/QuickstepLauncher; or its super classes (declaration of 'com.android.launcher3.uioverrides.QuickstepLauncher' appears in /data/app/~~R92ZHVsk9Gx91rH7jt5vPg==/app.lawnchair.debug-K_iM-TH0Qkb4LXd-NOEaoQ==/base.apk!classes11.dex)
	at com.android.launcher3.uioverrides.QuickstepLauncher.registerBackDispatcher(QuickstepLauncher.java:666)
	at com.android.launcher3.BaseActivity.onCreate(BaseActivity.java:200)
	at com.android.launcher3.BaseDraggingActivity.onCreate(BaseDraggingActivity.java:73)
	at com.android.launcher3.statemanager.StatefulActivity.onCreate(StatefulActivity.java:61)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:490)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:526)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:203)
	at android.app.Activity.performCreate(Activity.java:8060)
	at android.app.Activity.performCreate(Activity.java:8040)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3653)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3840)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:105)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:136)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7941)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

### PR DESCRIPTION
**Pull request by MrSluffy**
## Description

Once finish this should resolve the widget issues #2820 #3744, interacting in widgets and support in Q, R and S

## Type of change

:white_check_mark: General change (non-breaking change that doesn't fit the below categories like copyediting)
:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: quickstep/src/com/android/launcher3/statehandlers/DepthController.java [hunk 1]
```diff
@@ -134,8 +139,10 @@ public void setStateWithAnimation(LauncherState toState, StateAnimationConfig co
 
     @Override
     public void applyDepthAndBlur() {
-        ensureDependencies();
-        super.applyDepthAndBlur();
+        if(app.lawnchair.LawnchairApp.isAtleastT()){
```
Comment (yasanglass) [inline quickstep/src/com/android/launcher3/statehandlers/DepthController.java:142]:
```suggestion
        if (app.lawnchair.LawnchairApp.isAtleastT()) {
```

Comment (yasanglass) [reply quickstep/src/com/android/launcher3/statehandlers/DepthController.java:142]: The same issue is happening multiple times in this PR.

Comment (MrSluffy) [reply quickstep/src/com/android/launcher3/statehandlers/DepthController.java:142]: It's intended , cause if not this error occurs  : Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.NoSuchMethodError: No virtual method setWallpaperZoomOut(Landroid/os/IBinder;F)V in class Landroid/app/WallpaperManager; or its super classes (declaration of 'android.app.WallpaperManager' appears in /system/framework/framework.jar)
                                                                                                      at void com.android.quickstep.util.BaseDepthController.applyDepthAndBlur() (BaseDepthController.java:114)
                                                                                                      at void com.android.launcher3.statehandlers.DepthController.applyDepthAndBlur() (DepthController.java:143)
                                                                                                      at void com.android.launcher3.statehandlers.DepthController$1.onViewAttachedToWindow(android.view.View) (DepthController.java:85)
                                                                                                      at void com.android.launcher3.statehandlers.DepthController.ensureDependencies() (DepthController.java:98)
                                                                                                      at void com.android.launcher3.statehandlers.DepthController.applyDepthAndBlur() (DepthController.java:142)
                                                                                                      at void com.android.quickstep.util.BaseDepthController.setDepth(float) (BaseDepthController.java:159)

Comment (yasanglass) [reply quickstep/src/com/android/launcher3/statehandlers/DepthController.java:142]: Interesting! Okay, nevermind then. 👍🏼

**Review by yasanglass — APPROVED** [review]

File: lawnchair/src/app/lawnchair/LawnchairLauncher.kt [hunk 2]
```diff
@@ -299,12 +303,22 @@ class LawnchairLauncher :
...
     }
 
-//    fun shouldBackButtonBeHidden(toState: LauncherState): Boolean {
-//        if (toState == LauncherState.NORMAL && hasBackGesture) {
-//            return false
-//        }
-//        return super.shouldBackButtonBeHidden(toState)
-//    }
+    override fun registerBackDispatcher() {
+        if (VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
```
Comment (Goooler) [inline lawnchair/src/app/lawnchair/LawnchairLauncher.kt]:
```suggestion
        if (isAtleastT) {
```

File: systemUIShared/src/com/android/systemui/shared/system/BlurUtils.java [hunk 3]
```diff
@@ -29,7 +28,7 @@ public abstract class BlurUtils {
      * @return {@code true} when supported.
      */
     public static boolean supportsBlursOnWindows() {
-        return CROSS_WINDOW_BLUR_SUPPORTED && ActivityManager.isHighEndGfx()
+        return Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU && ActivityManager.isHighEndGfx()
```
Comment (Goooler) [inline systemUIShared/src/com/android/systemui/shared/system/BlurUtils.java:31]:
```suggestion
        return isAtleastT && ActivityManager.isHighEndGfx()
```

**Review by Goooler — APPROVED** [review]

**Review by SuperDragonXD — APPROVED** [review]

**Review by ThatOneCalculator — APPROVED** [review]
Tested and works. GrapheneOS Beta/Android 14 UP1A.231105.003.2023111500

**Review by divadsn — COMMENTED** [review]
LGTM, to be merged once suggestions from @Goooler are resolved.

**Comment by MrSluffy** [comment]
> LGTM, to be merged once suggestions from @Goooler are resolved.

I don't think we need to add atleastT in `BlurUtils` since it's in part of module. we want to avoid adding new field/var as much as possible in each module to avoid conflict wen merging. but in `LawnchairLauncher` it's done

File: lawnchair/src/app/lawnchair/LawnchairLauncher.kt (hunk 2 above)
Comment (MrSluffy) [reply lawnchair/src/app/lawnchair/LawnchairLauncher.kt]: done 7c9c32155b7c4a664567d09b5bb2e862c37db08d

File: lawnchair/src/app/lawnchair/LawnchairApp.kt [hunk 4]
```diff
@@ -201,6 +203,9 @@ class LawnchairApp : Application() {
         @JvmStatic
         val isRecentsEnabled: Boolean get() = instance.recentsEnabled
 
+        @JvmStatic
+        val isAtleastT: Boolean get() = instance.isAtleastT
```
Comment (suphon-t) [inline lawnchair/src/app/lawnchair/LawnchairApp.kt:207]: Why do we need this when we already have `Utilities.ATLEAST_T`?

File: quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java [hunk 5]
```diff
@@ -95,8 +95,7 @@ public class RecentsAnimationDeviceState implements DisplayInfoChangeListener {
     private final RotationTouchHelper mRotationTouchHelper;
     private final TaskStackChangeListener mPipListener;
     // Cache for better performance since it doesn't change at runtime.
-    private final boolean mCanImeRenderGesturalNavButtons =
-            InputMethodService.canImeRenderGesturalNavButtons();
+    private final boolean mCanImeRenderGesturalNavButtons = isImeRenderingNavButtons();
```
Comment (suphon-t) [inline quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java]: `isImeRenderingNavButtons` doesn't look like it can substitute `InputMethodService.canImeRenderGesturalNavButtons`.
I'd keep the call on A13 and fallback to a hardcoded value for older versions.

File: lawnchair/src/app/lawnchair/LawnchairApp.kt (hunk 4 above)
Comment (MrSluffy) [reply lawnchair/src/app/lawnchair/LawnchairApp.kt:207]: So we know that we're the one who applied when merging A14 so it will easy to fixing conflict

File: quickstep/src/com/android/launcher3/taskbar/NavbarButtonsViewController.java [hunk 6]
```diff
@@ -224,8 +224,7 @@ public void init(TaskbarControllers controllers) {
                         TaskbarManager.isPhoneMode(deviceProfile));
         mNavButtonsView.getLayoutParams().height = p.y;
 
-        mIsImeRenderingNavButtons =
-                InputMethodService.canImeRenderGesturalNavButtons() && mContext.imeDrawsImeNavBar();
+        mIsImeRenderingNavButtons = mContext.imeDrawsImeNavBar();
```
Comment (suphon-t) [inline quickstep/src/com/android/launcher3/taskbar/NavbarButtonsViewController.java]: Here as well

Comment (MrSluffy) [reply quickstep/src/com/android/launcher3/taskbar/NavbarButtonsViewController.java]: Done fp

**Review by suphon-t — APPROVED** [review]

**Review by Goooler — APPROVED** [review]
