### PR TITLE
Don't elevate priority for devices below Q

### LINKED ISSUE #3864: [BUG] Just Black Screen on Android 8
### Describe the bug

Here's me hoping that lawnchair will still be compatible on older Android versions such as Android 8😔

After installing lawnchair 13 debug version, and setting it as the default home screen, when going back to the home screen all I see is just black, no app response, no changes, just black, like the entirety of my screen is covered in black, waited for a couple of minutes or so but nothing happens.

### Steps to reproduce

You could possibly experience this only on Android 8 devices

Just download and install the latest Lawnchair (debug) 13 dev
After that open or use the launcher and then there the "black screen" problem

### Expected behavior

It's the Debug version so
I already expected bugs to happen, 

### Screenshots

Screenshot_2023-12-16-22-43-24-52

### Device information

- Device: Oppo A3s CPH1853
- OS: Android version 8.1.0, ColorOS version V5.2.1
- App version: Lawnchair (debug) 13 dev

### Additional context

_No response_

### LINKED ISSUE #4230: [BUG] Lawnchair 14 broken on all Android 8 devices
### Describe the bug

New Lawnchair 14 Beta doesn't work on any Android 8 device. Previous versions worked correctly. 

### Steps to reproduce

Just try to install Lawnchair 14 Beta on any Android 8 or 8.1 device and it won't start. I tried on a Lenovo (8.1), Motorola (8.1) and Huawei (8.0) device. 

### Expected behavior

I should be able to use and start Lawnchair or the minSdkVersion should be increased to a more recent version. 

### Screenshots

N/A because of nothing happens

### Device information

- Device: Lenovo Tab 4 8 and Motorola Moto G5S Plus
- OS: Stock Rom, Android 8.1.0
- App version: Lawnchair 14 Beta 1 and 2. Tried also with latest actions and nightly

### Additional context

_No response_

### LINKED ISSUE #4285: [BUG] Crash on Android 8
### Describe the bug

-

### Steps to reproduce

-

### Expected behavior

-

### Screenshots

_No response_

### Device information

- Device: Honor 7A Pro
- OS: EMUI 8.0.0 Android 8.0.0

### Additional context

Yes, I know that Android 8 is quite old and no longer receives updates, but I would still like this launcher on an old device

### PR DESCRIPTION
**Pull request by validcube**
EGL_CONTEXT_PRIORITY_HIGH_IMG doesn't exist for Android below Q and Lawnchair Launcher don't support QuickSwitch for below Android Q anyway, the effect should have no effect on daily usage.

Anyway the branch name is from small curry pie and it tasted delicious™️.

## Description

Fixes #4285 
Fixes #4230 
Fixes #3864

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: quickstep/src/com/android/quickstep/QuickstepProcessInitializer.java [hunk 1]
```diff
@@ -64,7 +64,7 @@ protected void init(Context context) {
 
                 // Elevate GPU priority for Quickstep and Remote animations.
                 try {
-                        ThreadedRenderer.setContextPriority(
+                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) ThreadedRenderer.setContextPriority(
```
Comment (Goooler) [inline quickstep/src/com/android/quickstep/QuickstepProcessInitializer.java]:
```suggestion
                        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) return;
                        ThreadedRenderer.setContextPriority(
```

File: quickstep/src/com/android/quickstep/QuickstepProcessInitializer.java [hunk 2]
```diff
@@ -64,6 +64,7 @@ protected void init(Context context) {
 
                 // Elevate GPU priority for Quickstep and Remote animations.
                 try {
+                        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) return;
```
Comment (validcube) [inline quickstep/src/com/android/quickstep/QuickstepProcessInitializer.java]: (self review's note) This could be replace with launcher3's atleast check

https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/src%2Fcom%2Fandroid%2Flauncher3%2FUtilities.java

Comment (MrSluffy) [reply quickstep/src/com/android/quickstep/QuickstepProcessInitializer.java]: Apply it thanks

**Review by MrSluffy — CHANGES_REQUESTED** [review]

File: quickstep/src/com/android/quickstep/QuickstepProcessInitializer.java (hunk 2 above)
Comment (validcube) [reply quickstep/src/com/android/quickstep/QuickstepProcessInitializer.java]: Applied @ https://github.com/LawnchairLauncher/lawnchair/pull/4331/commits/4190379172ce49d5fda69e704f001c1dd682f232

File: quickstep/src/com/android/quickstep/QuickstepProcessInitializer.java [hunk 3]
```diff
@@ -64,6 +65,7 @@ protected void init(Context context) {
 
                 // Elevate GPU priority for Quickstep and Remote animations.
                 try {
+                        if (Utilities.ATLEAST_Q) return;
```
Comment (Goooler) [inline quickstep/src/com/android/quickstep/QuickstepProcessInitializer.java]:
```suggestion
                        if (!Utilities.ATLEAST_Q) return;
```

Comment (validcube) [reply quickstep/src/com/android/quickstep/QuickstepProcessInitializer.java]: Whoops, accidentally forgot a check, thank.

**Review by MrSluffy — APPROVED** [review]

**Review by Goooler — APPROVED** [review]
