### PR TITLE
Fix crash on Android 9

### LINKED ISSUE #3778: [BUG] Lawchair 13 doesn't work on Android 9
### Describe the bug

The app simply doesn't work in these versions.
I don't use Quickstep and I don't even have Root

### Steps to reproduce

1. Install Lawnchair 13 on A9
2. Open it
3. Crash

### Expected behavior

Open normally

### Screenshots

_No response_

### Device information

- Device: an Old LG
- OS: [e.g. stock ROM Android version 9]
- App version: [e.g. 13.0.0]

### Additional context

```
Lawnchair (Debug) bug report 26 de nov de 2023 23:04:43
version: 13 Dev (#2388) (13)
commit: 5df1114
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.NoSuchMethodError: No static method createPredefined(I)Landroid/os/VibrationEffect; in class Landroid/os/VibrationEffect; or its super classes (declaration of 'android.os.VibrationEffect' appears in /system/framework/framework.jar!classes2.dex)
	at com.android.quickstep.util.VibrationConstants.<clinit>(VibrationConstants.java:22)
	at com.android.quickstep.views.RecentsView.<clinit>(RecentsView.java:294)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(StatefulActivity.java:85)
	at com.android.launcher3.Launcher.setupViews(Launcher.java:1353)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:222)
	at app.lawnchair.LawnchairLauncher.setupViews(LawnchairLauncher.kt:269)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:518)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:205)
	at android.app.Activity.performCreate(Activity.java:7159)
	at android.app.Activity.performCreate(Activity.java:7150)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

### PR DESCRIPTION
**Pull request by Rafael2616**
Fixes #3778 

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by MrSluffy** [comment]
There's some crashes still 

```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/policy/ScreenDecorationsUtils;
	at com.android.systemui.shared.system.QuickStepContract.supportsRoundedCornersOnWindows(QuickStepContract.java:384)
	at app.lawnchair.util.LawnchairUtilsKt.supportsRoundedCornersOnWindows(LawnchairUtils.kt:127)
	at com.android.quickstep.util.TaskCornerRadius.get(TaskCornerRadius.java:30)
	at com.android.quickstep.views.TaskView$FullscreenDrawParams.<init>(TaskView.java:1773)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:431)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:422)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:418)
	... 12 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.ScreenDecorationsUtils" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/lib/arm, /data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

You can try add condition here atleastq too [`supportsRoundedCornersOnWindows`](https://github.com/LawnchairLauncher/lawnchair/blob/13-dev/lawnchair/src/app/lawnchair/util/LawnchairUtils.kt#L123)

**Comment by Rafael2616** [comment]
> There's some crashes still 
> 
> ```
> Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/policy/ScreenDecorationsUtils;
> 	at com.android.systemui.shared.system.QuickStepContract.supportsRoundedCornersOnWindows(QuickStepContract.java:384)
> 	at app.lawnchair.util.LawnchairUtilsKt.supportsRoundedCornersOnWindows(LawnchairUtils.kt:127)
> 	at com.android.quickstep.util.TaskCornerRadius.get(TaskCornerRadius.java:30)
> 	at com.android.quickstep.views.TaskView$FullscreenDrawParams.<init>(TaskView.java:1773)
> 	at com.android.quickstep.views.TaskView.<init>(TaskView.java:431)
> 	at com.android.quickstep.views.TaskView.<init>(TaskView.java:422)
> 	at com.android.quickstep.views.TaskView.<init>(TaskView.java:418)
> 	... 12 more
> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.ScreenDecorationsUtils" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/lib/arm, /data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
> 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> ```
> 
> You can try add condition here atleastq too [`supportsRoundedCornersOnWindows`](https://github.com/LawnchairLauncher/lawnchair/blob/13-dev/lawnchair/src/app/lawnchair/util/LawnchairUtils.kt#L123)

Wow, that was a good start, 3 problems fixed with the same fix. My record

**Comment by Rafael2616** [comment]
What value should I put here for below Q, true or false?

```
    return QuickStepContract.supportsRoundedCornersOnWindows(context.resources)

```

**Comment by MrSluffy** [comment]
> What value should I put here for below Q, true or false?
> 
> ```
>     return QuickStepContract.supportsRoundedCornersOnWindows(context.resources)
> ```

false

**Comment by Rafael2616** [comment]
> > What value should I put here for below Q, true or false?
> > 
> > ```
> >     return QuickStepContract.supportsRoundedCornersOnWindows(context.resources)
> > ```
> 
> false
> 

Done 👍

**Comment by MrSluffy** [comment]
> > > What value should I put here for below Q, true or false?
> > > ```
> > >     return QuickStepContract.supportsRoundedCornersOnWindows(context.resources)
> > > ```
> > 
> > 
> > false
> 
> Done 👍

No, something like this and test it
```
fun getWindowCornerRadius(context: Context): Float {
    val prefs = getPrefsIfUnlocked(context)
    return when {
        prefs?.overrideWindowCornerRadius?.get() == true -> prefs.windowCornerRadius.get().toFloat()
        Utilities.ATLEAST_Q -> QuickStepContract.getWindowCornerRadius(context)
        else -> 0.0f
    }
}
```

**Comment by Rafael2616** [comment]
Sorry, I changed the wrong function

**Comment by Rafael2616** [comment]
I will correct it now

**Comment by Rafael2616** [comment]
Done again

**Comment by MrSluffy** [comment]
after build you can test

**Comment by MrSluffy** [comment]
> Done again

this too : 

```
fun supportsRoundedCornersOnWindows(context: Context): Boolean {
    val prefs = getPrefsIfUnlocked(context)

    return when {
        prefs?.overrideWindowCornerRadius?.get() == true -> true
        Utilities.ATLEAST_Q -> QuickStepContract.supportsRoundedCornersOnWindows(context.resources)
        else -> false
    }
}
```

**Comment by Rafael2616** [comment]
These other problem appeared
I'll continue tomorrow, as it's already late here

```
Lawnchair (Debug) bug report 1 de dez de 2023 03:55:47
version: 13 Dev (#2463) (13)
commit: 29f8a36
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/ISystemGestureExclusionListener$Stub;
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:158)
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:129)
	at com.android.quickstep.util.SplitWithKeyboardShortcutController.<init>(SplitWithKeyboardShortcutController.java:72)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:230)
	at app.lawnchair.LawnchairLauncher.setupViews(LawnchairLauncher.kt:272)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:518)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:208)
	at android.app.Activity.performCreate(Activity.java:7159)
	at android.app.Activity.performCreate(Activity.java:7150)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.ISystemGestureExclusionListener$Stub" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/lib/arm, /data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 23 more

```

**Comment by Rafael2616** [comment]
> These other problem appeared
> I'll continue tomorrow, as it's already late here
> 
> ```
> Lawnchair (Debug) bug report 1 de dez de 2023 03:55:47
> version: 13 Dev (#2463) (13)
> commit: 29f8a36
> build.brand: lge
> build.device: mmh4
> build.display: PKQ1.190522.001
> build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
> build.hardware: mmh4
> build.id: PKQ1.190522.001
> build.manufacturer: LGE
> build.model: LM-X420
> build.security.level: 2021-03-01
> build.product: mmh4_f
> build.type: user
> version.codename: REL
> version.incremental: 2106722188f70
> version.release: 9
> version.sdk_int: 28
> display.density_dpi: 280
> isRecentsEnabled: false
> 
> error: Uncaught exception
> 
> java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/ISystemGestureExclusionListener$Stub;
> 	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:158)
> 	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:129)
> 	at com.android.quickstep.util.SplitWithKeyboardShortcutController.<init>(SplitWithKeyboardShortcutController.java:72)
> 	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:230)
> 	at app.lawnchair.LawnchairLauncher.setupViews(LawnchairLauncher.kt:272)
> 	at com.android.launcher3.Launcher.onCreate(Launcher.java:518)
> 	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
> 	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:208)
> 	at android.app.Activity.performCreate(Activity.java:7159)
> 	at android.app.Activity.performCreate(Activity.java:7150)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:205)
> 	at android.app.ActivityThread.main(ActivityThread.java:6993)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
> Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.ISystemGestureExclusionListener$Stub" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/lib/arm, /data/app/app.lawnchair.debug-tmKROEOpm8nsss04spYktQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
> 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 	... 23 more
> 
> ```

This error happens because this method is not supported on Android 9 and below, but I'm not sure how to override this

```
android.view.ISystemGestureExclusionListener
```

He is called in this class

https://github.com/LawnchairLauncher/lawnchair/blob/4402ef1bf3722a4f203f0bc93f1851926af1712e/quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java#L158

Defined here:

https://github.com/LawnchairLauncher/lawnchair/blob/4402ef1bf3722a4f203f0bc93f1851926af1712e/systemUIShared/src/com/android/systemui/shared/system/SystemGestureExclusionListenerCompat.java#L33

**Comment by Rafael2616** [comment]
I limited this function to Android 10 +, maybe it will work now

**Comment by Rafael2616** [comment]
@MrSluffy Can you review my last commit and run it if it's correct, so I can see if there are any more problems launching the app?

**Comment by MrSluffy** [comment]
> Author

I can't test right now, but looks fine to me, test it now

**Comment by Rafael2616** [comment]
ok, I just need you to run the workflow when you can

**Comment by Rafael2616** [comment]
More one:

```
Lawnchair (Debug) bug report 1 de dez de 2023 21:26:18
version: 13 Dev (#2478) (13)
commit: 195618a
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair.debug/app.lawnchair.LawnchairLauncher}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.shared.system.SystemGestureExclusionListenerCompat.unregister()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3021)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.shared.system.SystemGestureExclusionListenerCompat.unregister()' on a null object reference
	at com.android.quickstep.RecentsAnimationDeviceState.onDisplayInfoChanged(RecentsAnimationDeviceState.java:266)
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:176)
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:129)
	at com.android.quickstep.util.SplitWithKeyboardShortcutController.<init>(SplitWithKeyboardShortcutController.java:72)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:230)
	at app.lawnchair.LawnchairLauncher.setupViews(LawnchairLauncher.kt:272)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:518)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:208)
	at android.app.Activity.performCreate(Activity.java:7159)
	at android.app.Activity.performCreate(Activity.java:7150)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
	... 11 more

```

**Comment by Rafael2616** [comment]
I added a null check, since the last commit made this `mExclusionListener` null below A10, since it was not initialized (because it is also not supported)

**Comment by Rafael2616** [comment]
I forgot `;`

**Comment by Rafael2616** [comment]
I fixed one more problem, now I'm in this

```
Lawnchair (Debug) bug report 2 de dez de 2023 21:21:32
version: 13 Dev (#9) (13)
commit: ee9e679
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.NoSuchMethodError: No virtual method getSourceLayoutResId()I in class Landroid/view/View; or its super classes (declaration of 'android.view.View' appears in /system/framework/framework.jar!classes2.dex)
	at com.android.launcher3.Workspace.setPageIndicatorInset(Workspace.java:412)
	at com.android.launcher3.Workspace.setInsets(Workspace.java:365)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:29)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:44)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:29)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:44)
	at com.android.launcher3.LauncherRootView.dispatchInsets(LauncherRootView.java:87)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:555)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:208)
	at android.app.Activity.performCreate(Activity.java:7159)
	at android.app.Activity.performCreate(Activity.java:7150)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

```

**Comment by Rafael2616** [comment]
I'm also running this on my GitHub Actions

**Comment by Rafael2616** [comment]
Related to the above error:

It looks like 'getSourceLayoutResId' It didn't work below 10, analyzing the code I saw that this has already been addressed elsewhere but not here

https://github.com/LawnchairLauncher/lawnchair/blob/13-dev/src%2Fcom%2Fandroid%2Flauncher3%2FWorkspace.java#L412

**Comment by Rafael2616** [comment]
Can I simply check what the version is and set a value if it is below 10? If yes, what value, false or true?

**Comment by Rafael2616** [comment]
New problem, resource not found 

`android.R.color.system_accent3_200 `

```
Lawnchair (Debug) bug report 2 de dez de 2023 23:12:32
version: 13 Dev (#12) (13)
commit: efc4841
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

android.content.res.Resources$NotFoundException: Resource ID #0x1060055
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:230)
	at android.content.res.Resources.getColor(Resources.java:964)
	at com.android.launcher3.BubbleTextView.applyIconAndLabel(BubbleTextView.java:396)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:347)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:317)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:312)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1430)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1415)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:2525)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:2486)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$bindWorkspaceItems$7(BaseLauncherBinder.java:331)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda10.execute(Unknown Source:6)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$executeCallbacksTask$9(BaseLauncherBinder.java:352)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.$r8$lambda$a4Qxm57bpz83-gfmBrdCLjV8bf4(Unknown Source:0)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda9.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

```

**Comment by Rafael2616** [comment]
Ok, this is the newest problem and I don't know how to solve it
The method 'viewRootImpl.getSurfaceControl()' It's not available on Android 9 and I don't know how to replace it here 

```
private void onLauncherDraw() {
        View view = mLauncher.getDragLayer();
        ViewRootImpl viewRootImpl = view.getViewRootImpl();
        setSurface(viewRootImpl != null ? viewRootImpl.getSurfaceControl() : null);
        view.post(() -> view.getViewTreeObserver().removeOnDrawListener(mOnDrawListener));
    }

```

**Comment by Rafael2616** [comment]
I did it, now it works 🎉🎉😅

**Comment by Rafael2616** [comment]
No very obvious crashes so far, in fact, no crashes at all, Only the dock search bar is squeezed. But it works

File: quickstep/src/com/android/launcher3/statehandlers/DepthController.java [hunk 1]
```diff
@@ -174,4 +185,4 @@ public void dump(String prefix, PrintWriter writer) {
         writer.println(prefix + "\tmIgnoreStateChangesDuringMultiWindowAnimation="
                 + mIgnoreStateChangesDuringMultiWindowAnimation);
     }
-}
\ No newline at end of file
+}
```
Comment (MrSluffy) [inline quickstep/src/com/android/launcher3/statehandlers/DepthController.java]: Clean up, don't add unneccsary spacing

File: quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java [hunk 2]
```diff
@@ -208,6 +210,7 @@ public void onExclusionChanged(Region region) {
         } catch (RemoteException e) {
             // Do nothing
         }
+
```
Comment (MrSluffy) [inline quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java]: this too

File: quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java [hunk 3]
```diff
@@ -258,6 +263,10 @@ public void onDisplayInfoChanged(Context context, Info info, int flags) {
             mMode = info.navigationMode;
             mNavBarPosition = new NavBarPosition(mMode, info);
 
+            if (mExclusionListener == null) {
```
Comment (MrSluffy) [inline quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java]: `if (mExclusionListener == null) return`

File: src/com/android/launcher3/BubbleTextView.java [hunk 4]
```diff
@@ -389,11 +389,17 @@ protected void setItemInfo(ItemInfoWithIcon itemInfo) {
...
+            mColor = android.R.color.system_accent3_200;
+        } else {
+            mColor = android.R.color.transparent;
+        }
         boolean useTheme = shouldUseTheme();
         FastBitmapDrawable iconDrawable = info.newIcon(getContext(), useTheme);
         mDotParams.appColor = iconDrawable.getIconColor();
         mDotParams.color = getContext().getResources()
-                .getColor(android.R.color.system_accent3_200, getContext().getTheme());
+                .getColor(mColor, getContext().getTheme());
```
Comment (MrSluffy) [inline src/com/android/launcher3/BubbleTextView.java]:
```
mDotParams.color = iconDrawable.getIconColor();
```

File: src/com/android/launcher3/BubbleTextView.java [hunk 5]
```diff
@@ -389,11 +389,17 @@ protected void setItemInfo(ItemInfoWithIcon itemInfo) {
 
     @UiThread
     protected void applyIconAndLabel(ItemInfoWithIcon info) {
+        int mColor;
+        if (Utilities.ATLEAST_Q) {
```
Comment (MrSluffy) [inline src/com/android/launcher3/BubbleTextView.java]: remove this

File: quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java [hunk 6]
```diff
@@ -216,12 +219,14 @@ public void onActivityPinned(String packageName, int userId, int taskId, int sta
 
             @Override
             public void onActivityUnpinned() {
-                mPipIsActive = false;
+               mPipIsActive = false;
```
Comment (MrSluffy) [inline quickstep/src/com/android/quickstep/RecentsAnimationDeviceState.java]: this too

File: quickstep/src/com/android/launcher3/statehandlers/DepthController.java [hunk 7]
```diff
@@ -64,7 +67,15 @@ public DepthController(Launcher l) {
     private void onLauncherDraw() {
         View view = mLauncher.getDragLayer();
         ViewRootImpl viewRootImpl = view.getViewRootImpl();
-        setSurface(viewRootImpl != null ? viewRootImpl.getSurfaceControl() : null);
+        if (Utilities.ATLEAST_Q) {
+            setSurface(viewRootImpl != null ? viewRootImpl.getSurfaceControl() : null);
+        } else {
+            Bitmap bitmap = view.getDrawingCache();
```
Comment (MrSluffy) [inline quickstep/src/com/android/launcher3/statehandlers/DepthController.java]: why do we need this? exactly?

**Review by MrSluffy — CHANGES_REQUESTED** [review]

File: quickstep/src/com/android/launcher3/statehandlers/DepthController.java (hunk 7 above)
Comment (Rafael2616) [reply quickstep/src/com/android/launcher3/statehandlers/DepthController.java]: In fact it was the equivalent replacement that I found for the "setSurface" function with the method that is incompatible, I don't know if just leaving it without it will work.

Comment (Rafael2616) [reply quickstep/src/com/android/launcher3/statehandlers/DepthController.java]: > why do we need this? exactly?

And i also need to convert Bitmap to Canvas

File: src/com/android/launcher3/BubbleTextView.java (hunk 4 above)
Comment (Rafael2616) [reply src/com/android/launcher3/BubbleTextView.java]: This caused the app to crash again
```
Lawnchair (Debug) bug report 3 de dez de 2023 02:33:03
version: 13 Dev (#22) (13)
commit: 7c3c8d5
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

android.content.res.Resources$NotFoundException: Resource ID #0xff8ab1e7
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:230)
	at android.content.res.Resources.getColor(Resources.java:964)
	at com.android.launcher3.BubbleTextView.applyIconAndLabel(BubbleTextView.java:396)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:347)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:317)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:312)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1430)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1415)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:2525)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:2486)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$bindWorkspaceItems$7(BaseLauncherBinder.java:331)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda10.execute(Unknown Source:6)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$executeCallbacksTask$9(BaseLauncherBinder.java:352)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.$r8$lambda$a4Qxm57bpz83-gfmBrdCLjV8bf4(Unknown Source:0)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda9.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

```

**Comment by MrSluffy** [comment]
> No very obvious crashes so far, in fact, no crashes at all, Only the dock search bar is squeezed. But it works

Great, I pushed some changes, kindly test once build, 

and for the tight dock, it will be fix in diff since there's already open issue about it

File: src/com/android/launcher3/BubbleTextView.java [hunk 8]
```diff
@@ -392,8 +392,7 @@ protected void applyIconAndLabel(ItemInfoWithIcon info) {
         boolean useTheme = shouldUseTheme();
         FastBitmapDrawable iconDrawable = info.newIcon(getContext(), useTheme);
         mDotParams.appColor = iconDrawable.getIconColor();
-        mDotParams.color = getContext().getResources()
-                .getColor(android.R.color.system_accent3_200, getContext().getTheme());
+        mDotParams.color = iconDrawable.getIconColor();
```
Comment (suphon-t) [inline src/com/android/launcher3/BubbleTextView.java]: Lawnchair has a color theming system for these dynamic colors. Please add accent3_200 [here](https://github.com/LawnchairLauncher/lawnchair/blob/13-dev/lawnchair/src/app/lawnchair/theme/color/ColorTokens.kt) and use it instead.

File: lawnchair/res/values-v28/colors.xml [hunk 9]
```diff
@@ -0,0 +1,5 @@
+<?xml version="1.0" encoding="utf-8"?>
+<resources>
+    <color name="system_accent1_100">@android:color/transparent</color>
```
Comment (suphon-t) [inline lawnchair/res/values-v28/colors.xml:3]: Please use something more appropriate than transparent. This can cause visual glitches or even crashes in some places.

Comment (Rafael2616) [reply lawnchair/res/values-v28/colors.xml:3]: What color would you think is appropriate as I'm just using the same solution as was used to fix crash on Android 10, 11 by @MrSluffy

File: src/com/android/launcher3/BubbleTextView.java (hunk 8 above)
Comment (Rafael2616) [reply src/com/android/launcher3/BubbleTextView.java]: @MrSlufffy Could you do this?

**Comment by MrSluffy** [comment]
I revert the merged as it messes with the file changed

**Comment by Rafael2616** [comment]
Ok

**Comment by Rafael2616** [comment]
Could you see that

https://github.com/LawnchairLauncher/lawnchair/pull/3808#discussion_r1412912415

**Comment by Rafael2616** [comment]
And Here

https://github.com/LawnchairLauncher/lawnchair/pull/3808#discussion_r1413083124

**Comment by Rafael2616** [comment]
How to solve this after applying @suphon-t suggestion

/home/runner/work/lawnchair/lawnchair/src/com/android/launcher3/BubbleTextView.java:396: error: Accent3_200 has private access in ColorTokens

**Comment by Rafael2616** [comment]
Thanks

**Comment by Rafael2616** [comment]
It still works 👍. it needs only my 1 review comments above so it's ready to merge

**Review by MrSluffy — APPROVED** [review]

**Comment by Rafael2616** [comment]
I fixed this problem more, could you check 
(Ocurrs when going to the recents screen when you have a folder open or are editing a widget)

I also prevented other errors from occurring due to the use of the same class that do not exist here

https://github.com/LawnchairLauncher/lawnchair/assets/93414086/1a63fc37-9861-4704-aa01-e6bec79a9106

File: systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java [hunk 10]
```diff
@@ -70,8 +73,10 @@ public class ActivityManagerWrapper {
     // Should match the value in AssistManager
     private static final String INVOCATION_TIME_MS_KEY = "invocation_time_ms";
 
-    private final ActivityTaskManager mAtm = ActivityTaskManager.getInstance();
-    private ActivityManagerWrapper() { }
+    private final ActivityTaskManager mAtm;
+    private ActivityManagerWrapper() {
```
Comment (MrSluffy) [inline systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java]: this will cause issue in upper version

File: systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java [hunk 11]
```diff
@@ -70,8 +73,10 @@ public class ActivityManagerWrapper {
...
+        mAtm = atleastQ ? ActivityTaskManager.getInstance() : null;
```
Comment (MrSluffy) [inline systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java]: this too

File: systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java [hunk 12]
```diff
@@ -345,10 +352,16 @@ public boolean showVoiceSession(IBinder token, Bundle args, int flags) {
     public boolean supportsFreeformMultiWindow(Context context) {
         final boolean freeformDevOption = Settings.Global.getInt(context.getContentResolver(),
                 Settings.Global.DEVELOPMENT_ENABLE_FREEFORM_WINDOWS_SUPPORT, 0) != 0;
-        return ActivityTaskManager.supportsMultiWindow(context)
-                && (context.getPackageManager().hasSystemFeature(
-                PackageManager.FEATURE_FREEFORM_WINDOW_MANAGEMENT)
-                || freeformDevOption);
+        if (atleastQ) {
```
Comment (MrSluffy) [inline systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java]: this too

File: systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java (hunk 10 above)
Comment (Rafael2616) [reply systemUIShared/src/com/android/systemui/shared/system/ActivityManagerWrapper.java]: Okay, we don't want that to happen 😂. What must be done then to make it work in both?

File: lawnchair/res/values-v28/colors.xml (hunk 9 above)
Comment (suphon-t) [reply lawnchair/res/values-v28/colors.xml:3]: Let's leave it like this for now if you say it works

**Comment by Rafael2616** [comment]
@MrSluffy Could I just revert the last change so this can be merged and then fix this in a separate PR since it doesn't significantly affect usage? So much so that I only noticed it after 5 days of use. Or do you intend to correct it soon?

**Comment by MrSluffy** [comment]
> @MrSluffy Could I just revert the last change so this can be merged and then fix this in a separate PR since it doesn't significantly affect usage? So much so that I only noticed it after 5 days of use. Or do you intend to correct it soon?

sure, I'll check it later

**Comment by Rafael2616** [comment]
I'll create an issue for this specific issue soon

**Comment by MrSluffy** [comment]
I think the crash in `java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/ActivityTaskManager;` are similar with this 282edc72a65057821d65fc303e4e92ad99a3fec3 , it should work once merge

**Comment by Rafael2616** [comment]
> I think the crash in `java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/ActivityTaskManager;` are similar with this 282edc72a65057821d65fc303e4e92ad99a3fec3 , it should work once merge

Yes, this problem no longer occurred after the merge 👍
