### PR TITLE
Automatic icon reload on night mode change

### LINKED ISSUE #2882: [BUG] Dynamic Iconpacks wont automatically update
### Describe the bug

When Darkmode turns on/off my dynamic Iconpack wont auto update. 
In Lawnchair v12.0 this was still working when Lawnicons wasnt out yet.
Now in Lawnchair v12.1 (and above, even developer) it doesnt work anymore.
Only Lawnicons itself gets auto updated.

### Steps to reproduce

1. Install 3rd party dynamic Iconpack
2. Set it as ur Iconpack
3. Enable or disable darkmode
4. Look at icons

### Expected behavior

Icons should auto update to either darkmode or lightmode

### Screenshots

Screenshot_20220825-170033

### Device information

- Device: [e.g. Google Pixel 6 Pro]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4 / Dev # 1048]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yasanglass**
## Description

This PR makes _Lawnchair_ listen to `uiMode` configuration changes & reload icons when night mode changes.

Fixes the night mode part of #2882

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: lawnchair/src/app/lawnchair/LawnchairLauncher.kt [hunk 1]
```diff
@@ -157,11 +159,13 @@ class LawnchairLauncher : QuickstepLauncher(), LifecycleOwner,
     val gestureController by lazy { GestureController(this) }
     private val defaultOverlay by lazy { OverlayCallbackImpl(this) }
     private val prefs by lazy { PreferenceManager.getInstance(this) }
+    private val preferenceManager by lazy { PreferenceManager.getInstance(this) }
```
Comment (Goooler) [inline lawnchair/src/app/lawnchair/LawnchairLauncher.kt]: Why not use `prefs`?

File: lawnchair/src/app/lawnchair/LawnchairLauncher.kt [hunk 2]
```diff
@@ -390,6 +403,27 @@ class LawnchairLauncher : QuickstepLauncher(), LifecycleOwner,
...
+        return newConfig.diff(mOldConfig) and ActivityInfo.CONFIG_UI_MODE != 0 && isOnDarkMode(
+            newConfig
+        ) != isOnDarkMode(
+            mOldConfig!!
+        )
+    }
+
+    private fun isOnDarkMode(configuration: Configuration): Boolean {
+        return configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK == Configuration.UI_MODE_NIGHT_YES
+    }
```
Comment (Goooler) [inline lawnchair/src/app/lawnchair/LawnchairLauncher.kt]:
```suggestion
    private fun isNightConfigChanged(newConfig: Configuration): Boolean {
        return newConfig.diff(mOldConfig) and ActivityInfo.CONFIG_UI_MODE != 0 &&
            newConfig.isOnDarkMode() != mOldConfig?.isOnDarkMode()
    }

    private fun Configuration.isOnDarkMode(): Boolean {
        return uiMode and Configuration.UI_MODE_NIGHT_MASK == Configuration.UI_MODE_NIGHT_YES
    }
```

File: lawnchair/src/app/lawnchair/LawnchairLauncher.kt (hunk 1 above)
Comment (yasanglass) [reply lawnchair/src/app/lawnchair/LawnchairLauncher.kt]: Uh, I didn't notice its already added because preferenceManager2 was added by its full name. Ill fix it now.

**Review by Goooler — APPROVED** [review]

File: lawnchair/src/app/lawnchair/LawnchairLauncher.kt [hunk 3]
```diff
@@ -407,8 +407,10 @@ class LawnchairLauncher : QuickstepLauncher(), LifecycleOwner,
      */
     private fun forceReloadIcons() {
         val iconPack = prefs.iconPackPackage.get()
-        prefs.iconPackPackage.set("")
-        prefs.iconPackPackage.set(iconPack)
+        if (iconPack != "") {
+            prefs.iconPackPackage.set("")
+            prefs.iconPackPackage.set(iconPack)
+        }
```
Comment (Goooler) [inline lawnchair/src/app/lawnchair/LawnchairLauncher.kt:415]: Revert or use below?

```suggestion
        if (iconPack != "") {
            prefs.iconPackPackage.set("")
        }
        prefs.iconPackPackage.set(iconPack)
```

Comment (yasanglass) [reply lawnchair/src/app/lawnchair/LawnchairLauncher.kt:415]: Why? we don't have to set it to the original value if we never change it.

Comment (Goooler) [reply lawnchair/src/app/lawnchair/LawnchairLauncher.kt:415]: Sorry, missread it.
