### PR TITLE
Fixed weather at glance

### LINKED ISSUE #3666: [BUG] no more weather on at a glance after new Google app update
### Describe the bug

With new update from Google app the weather is not showed any more

### Steps to reproduce

1. Go to 'home settings'
2. Click on 'at a glance'
3. Scroll down to 'at a glance provider select lawchair and select show weather'

### Expected behavior

Weather must be showed at a glance 

### Screenshots

/
Screenshot_20231014-063138

### Device information

- Device: [Sony Xperia 1 mark 4]
- OS: [stock ROM Android version 13.0]
- App version: [12.1.0 Alpha 4]

### Additional context

_No response_

### LINKED ISSUE #3701: [BUG] At a glance is not showing weather info on Android 14, Pixel 7
### Describe the bug

The at a glance widget is not showing weather information on Android 14

### Steps to reproduce

1. Go to home screen of Pixel 7 running on Android 14 
2. See at a glance widget, it only shows date, weather details not showing 

### Expected behavior

At a glance widget should show weather details

### Screenshots

_No response_

### Device information

- Device:  Google Pixel 7
- OS: stock ROM Android version 14
- App version: 12.1.0 Alpha 4

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MrSluffy**
## Description

- Closes : #3701 
- Closes : #3666

BeFunky-collage (2)

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by suphon-t — APPROVED** [review]

File: lawnchair/src/app/lawnchair/smartspace/provider/SmartspaceWidgetReader.kt [hunk 1]
```diff
@@ -57,9 +57,9 @@ class SmartspaceWidgetReader(context: Context) : SmartspaceDataSource(
     }
 
     private fun extractWidgetLayout(appWidgetHostView: ViewGroup): List<SmartspaceTarget> {
-        val children = appWidgetHostView.recursiveChildren.filter { it.isVisible }
+        val children = appWidgetHostView.recursiveChildren
         val texts = children.filterIsInstance<TextView>().filter { !it.text.isNullOrEmpty() }.toList()
-        val images = children.filterIsInstance<ImageView>().toList()
+        val images = children.filterIsInstance<ImageView>().toList().filter { it.drawable != null && it.drawable is BitmapDrawable }
```
Comment (Goooler) [inline lawnchair/src/app/lawnchair/smartspace/provider/SmartspaceWidgetReader.kt:62]: `t.drawable is BitmapDrawable` should be enough.

**Review by Goooler — APPROVED** [review]

File: lawnchair/src/app/lawnchair/smartspace/provider/SmartspaceWidgetReader.kt (hunk 1 above)
Comment (MrSluffy) [reply lawnchair/src/app/lawnchair/smartspace/provider/SmartspaceWidgetReader.kt:62]: Already tried and isnt working maybe due to layers in new google at glance widget layout
