### PR TITLE
Patch fix for Android 13 and below

### LINKED ISSUE #4965: [BUG] Lawnchair crashes in `15-dev` branch
### Describe the bug

backtrace
```
java.lang.NoSuchMethodError: No static method enableDesktopWindowingWallpaperActivity()Z in class Lcom/android/window/flags/Flags; or its super classes (declaration of 'com.android.window.flags.Flags' appears in /system/framework/framework.jar!classes5.dex)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setResumed(QuickstepLauncher.java:993)
	at com.android.launcher3.BaseActivity.onResume(BaseActivity.java:226)
	at com.android.launcher3.statemanager.StatefulActivity.onResume(StatefulActivity.java:163)
	at com.android.launcher3.Launcher.onResume(Launcher.java:1323)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onResume(QuickstepLauncher.java:783)
	at app.lawnchair.LawnchairLauncher.onResume(LawnchairLauncher.kt:327)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
	at android.app.Activity.performResume(Activity.java:9118)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5234)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5277)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:331)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

Downgrade to version before https://github.com/LawnchairLauncher/lawnchair/commit/54fe46d75d94c05b819f5fc0276d805985659a20, the issue disappeared.

### Steps to reproduce

1. Install new lawnchair.
2. Lawnchair crashed.

### Expected behavior

Works normally.

### Screenshots

_No response_

### Device information

- Device: Redmi K40
- OS: Lineage OS 21 (Android 14)
- App version: 15.Dev.(#1575)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rafael2616**
tested in Android 9, 10 and 13 and works fine.

## Description

- Closes : #4965

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: src/com/android/launcher3/util/window/WindowManagerProxy.java [hunk 1]
```diff
@@ -127,11 +127,17 @@ public boolean isInDesktopMode() {
      * normalization
      */
     public WindowBounds getRealBounds(Context displayInfoContext, CachedDisplayInfo info) {
-        WindowMetrics windowMetrics = displayInfoContext.getSystemService(WindowManager.class)
-                .getMaximumWindowMetrics();
+        WindowMetrics windowMetrics;
+        if (Utilities.ATLEAST_R) {
+            windowMetrics = displayInfoContext.getSystemService(WindowManager.class)
+                    .getMaximumWindowMetrics();
+
```
Comment (MrSluffy) [inline src/com/android/launcher3/util/window/WindowManagerProxy.java]: Can we use the [LawnchairWindowManagerProxy](https://github.com/LawnchairLauncher/lawnchair/blob/b86b188307eccde278e0761b7bc7724ffe05ae5c/lawnchair/src/app/lawnchair/util/LawnchairWindowManagerProxy.kt#L14) instead of modifying this? Thanks!

**Review by MrSluffy — CHANGES_REQUESTED** [review]

File: src/com/android/launcher3/util/window/WindowManagerProxy.java (hunk 1 above)
Comment (Rafael2616) [reply src/com/android/launcher3/util/window/WindowManagerProxy.java]: if you are talking about the `estimateInternalDisplayBounds(context)` method i tried here, but the return type is different and the most i could achive was `WindowBounds` and the expected type is `WindowInfo` and i not know if is posssible and how do this conversion

Comment (MrSluffy) [reply src/com/android/launcher3/util/window/WindowManagerProxy.java]: Alright, let me do it

Comment (Rafael2616) [reply src/com/android/launcher3/util/window/WindowManagerProxy.java]: Sure
