### PR TITLE
Be easier to trigger fast scroller in app drawer

### LINKED ISSUE #3126: [BUG] Hard to trigger fast scroller in app drawer
### Describe the bug

I can't trigger the fast scroller on my OnePlus 8t, I've also tried it out on Pixel 6 and Samsung S8, and it's hard to trigger.

### Steps to reproduce

https://user-images.githubusercontent.com/10363352/203715095-4471cd6b-b1a9-403a-ae0d-9eaf3fbb26aa.mp4

### Expected behavior

Can trigger it easily, we may need to expand the touch scope in width to recognize drag gestures in the app drawer.

### Screenshots

_No response_

### Device information

- Device: OnePlus 8t
- OS: Android 11
- App version: the latest

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Goooler**
## Description

Closes #3126.

https://user-images.githubusercontent.com/10363352/213102001-18684571-fc00-4f00-a640-dd655008e092.mp4

VS

https://user-images.githubusercontent.com/10363352/213102714-93c35918-a293-431f-9b6f-94962c261a74.mov

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

File: src/com/android/launcher3/views/RecyclerViewFastScroller.java [hunk 1]
```diff
@@ -58,7 +58,7 @@
 public class RecyclerViewFastScroller extends View {
     private static final String TAG = "RecyclerViewFastScroller";
     private static final boolean DEBUG = false;
-    private static final int FASTSCROLL_THRESHOLD_MILLIS = 40;
+    private static final int FASTSCROLL_THRESHOLD_MILLIS = 10;
```
Comment (Goooler) [inline src/com/android/launcher3/views/RecyclerViewFastScroller.java:61]: `ev.getEventTime() - mDownTimeStampMillis > FASTSCROLL_THRESHOLD_MILLIS` usually be false before, hard to trigger `mIsDragging`.

https://github.com/LawnchairLauncher/lawnchair/blob/0e8a2ce0a9024a52f1a0593a884de86e1f5fcd23/src/com/android/launcher3/views/RecyclerViewFastScroller.java#L275-L280

https://github.com/LawnchairLauncher/lawnchair/blob/0e8a2ce0a9024a52f1a0593a884de86e1f5fcd23/src/com/android/launcher3/views/RecyclerViewFastScroller.java#L308-L309

**Comment by Goooler** [comment]
Would like to listen to your feedbacks after applying this change on your phones.

**Comment by Goooler** [comment]
@suphon-t Any idea?
