### PR TITLE
fix: Reimplement folder label in dock toggle

### LINKED ISSUE #6380: "Show labels" not working for folders in dock
### Describe the bug

when activating "Show labels" in /settings/Dock it only works for singe apps, but not for folders.
works well on the "home screen" but not in the dock.

### Steps to reproduce

when activating "Show labels" in /settings/Dock it only works for singe apps, but not for folders

### Expected behavior

folder name shown in dock

### Screenshots

_No response_

### Device information

Fairphone 4 with latest /e/os

### App version

15

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wellorbetter**
### Description

Folder icons in the dock now respect the "Show labels" dock preference instead of always hiding their label.

Fixes #6380

### Reasoning

`WorkspaceLayoutManager` unconditionally called `setTextVisible(false)` for `FolderIcon` in the hotseat, ignoring the `enableLabelInDock` preference. `BubbleTextView` already handled this correctly in `CellLayout`.

### Testing

1. Place a folder in the dock
2. Go to Settings → Dock → enable "Show labels"
3. Folder label should now be visible in the dock

### Type of change

:white_check_mark: **Bug fix** (A non-breaking change that fixes an issue)
:x: **New feature** (A non-breaking change that adds functionality)
:x: **Breaking change** (A fix or feature that would cause existing functionality to not work as expected)
:x: **Refactor** (A code change that neither fixes a bug nor adds a feature)
:x: **Performance** (A code change that improves performance)
:x: **Style** (Code style changes)
:x: **Docs** (Changes to documentation)
:x: **Chore** (Changes to the build process or other tooling)

## Summary by CodeRabbit

* **Bug Fixes**
  * Dock (hotseat) folder labels now respect the "show labels in dock" preference instead of always being hidden. Folder titles in the dock will now appear or remain hidden according to your launcher setting, matching label behavior on the home screen and ensuring consistent visibility between dock and workspace.

### CODE REVIEW

**Review by wellorbetter — COMMENTED** [review]
It's a small fix for #6380 — folder icons in the dock now respect the "Show labels" preference. Only one file changed.

File: src/com/android/launcher3/WorkspaceLayoutManager.java [hunk 1]
```diff
@@ -105,9 +108,12 @@ default void addInScreen(View child, int container, int screenId, int x, int y,
...
             layout = getHotseat();
 
-            // Hide folder title in the hotseat
+            // Show/hide folder title based on dock label preference
             if (child instanceof FolderIcon) {
-                ((FolderIcon) child).setTextVisible(false);
+                ((FolderIcon) child).setTextVisible(
+                        PreferenceExtensionsKt.firstBlocking(
+                                PreferenceManager2.getInstance(child.getContext())
+                                        .getEnableLabelInDock()));
```
Comment (validcube) [inline src/com/android/launcher3/WorkspaceLayoutManager.java]: Keep the original Launcher3 comment the same and create our own comment prefixed by `LC-Note` so that it will be easy to identify, and rebase the feature on top of the latest Launcher3 version.

```suggestion
            // Hide folder title in the hotseat
if (child instanceof FolderIcon) {
                ((FolderIcon) child).setTextVisible(
                        PreferenceExtensionsKt.firstBlocking(
                                PreferenceManager2.getInstance(child.getContext())
                                        .getEnableLabelInDock())); // LC-Note: Show/hide folder title based on dock label preference
```

**Review by validcube — APPROVED** [review]
Overall LGTM with nitpick suggestion.

File: src/com/android/launcher3/WorkspaceLayoutManager.java (hunk 1 above)
Comment (wellorbetter) [reply src/com/android/launcher3/WorkspaceLayoutManager.java]: Done. Kept the original AOSP comment and added LC-Note inline. Already rebased on latest 16-dev.

**Review by validcube — APPROVED** [review]
Final approval
